### ISSUE TITLE
Composer Installation

### ISSUE THREAD

**Issue by alexander-torosh** [mwillbanks/ZfcTwitterBootstrap#10]
The requested package zfctwitterbootstrap master could not be found.

Using code from README.md Installation

**Comment by mwillbanks** [comment]
webtor this usually happens because of your preferred stability state in composer; try setting the following to "dev": http://getcomposer.org/doc/04-schema.md#minimum-stability

"minimum-stability": "dev"

inside of the root tag on your composer.json file.

**Comment by mwillbanks** [comment]
I will look at adding this to packagist here soon as well.

**Comment by mwillbanks** [comment]
Sorry for the delay; this has been completed: https://packagist.org/packages/mwillbanks/zfc-twitter-bootstrap
