### ISSUE TITLE
MultiCheckbox class missing

### ISSUE THREAD

**Issue by Chuvisco88** [mwillbanks/ZfcTwitterBootstrap#27]
While testing your module we discovered that the label for MultiCheckbox does not have the class "checkbox" set.
The following code (added to FormElement.php) fixes this issue:

``` php
if (method_exists($renderer, 'plugin')) {
    if ($element instanceof \Zend\Form\Element\MultiCheckbox) {
        $renderer->plugin('form_multi_checkbox')->setLabelAttributes(array(
            'class' => 'checkbox',
        ));
    }
}
```

**Comment by mwillbanks** [comment]
Sure can you send a PR?  If not; I will work on this later on today.   I haven't had a ton of time to improve some of the view helpers and making them more flexible by form element type.
