### ISSUE TITLE
renderFieldset does not handle attributes or legend

### ISSUE THREAD

**Issue by personman** [mwillbanks/ZfcTwitterBootstrap#31]
I'm rendering a form like this:

```
$this->ztbForm($form);
```

But the output does not include the fieldset's legend or class, which I set like this:

```
$buttons = new Fieldset('buttons');
$buttons->setAttribute('class', 'well well-small');
$buttons->setLabel('My Legend');
```

Here is the ZfcTwitterBootstrap's renderFieldset method:

```
public function renderFieldset(Fieldset $fieldset)
{
    $id = $fieldset->getAttribute('id') ?: $fieldset->getName();

    return '<fieldset id="fieldset-' . $id . '">'
        . $this->render($fieldset)
        . '</fieldset>';
}
```

If you're ok with it, I'll add the legend (when there's a non-empty label) and the fieldset's class and then send a pull request. Is there anything else I should include in this change? Or is there any reason I shouldn't make this change?

**Comment by mwillbanks** [comment]
Is that the way it is handled in both bootstrap and zf2?  If so I certainly agree it should be added and we should have a PR for it :)

**Comment by personman** [comment]
I'm not sure what you mean by your question, but I'll plan on submitting a PR with the change this week.

**Comment by personman** [comment]
I just updated via Composer and confirmed that the fieldset is now displayed. Thanks for merging!
