### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by ThaDafinser** [mwillbanks/ZfcTwitterBootstrap#37]
What kind of License is this?

Please provide one :-)

**Comment by mwillbanks** [comment]
Sorry about that; yes; I should certainly add one.  Will be same license as Zend license.

**Comment by ThaDafinser** [comment]
@mwillbanks is your respository linked to packagist right?

Since it still don't show the license: https://packagist.org/packages/mwillbanks/zfc-twitter-bootstrap

2nd thing: Please create some the tag for searching in packagist: ZfcTwitterBootstrap,

**Comment by ThaDafinser** [comment]
Thanks for license :)
