### ISSUE TITLE
 'Class ZfcTwitterBootstrap\Form\View\Helper\FormElement does not exist'

### ISSUE THREAD

**Issue by ghost** [mwillbanks/ZfcTwitterBootstrap#6]
Hi.
When i do 
echo $this->formRenderer($this->formulaire); into my view:
I get :
Fatal error: Uncaught exception 'ReflectionException' with message 'Class ZfcTwitterBootstrap\Form\View\Helper\FormElement does not exist' in vendor\zendframework\zendframework\library\Zend\Code\Reflection\ParameterReflection.php:47 
Stack trace: #0 vendor\zendframework\zendframework\library\Zend\Code\Reflection\ParameterReflection.php(47): ReflectionParameter->getClass() 
#1 vendor\zendframework\zendframework\library\Zend\Di\Definition\RuntimeDefinition.php(348): Zend\Code\Reflection\ParameterReflection->getClass()
#2 vendor\zendframework\zendframework\library\Zend\Di\Definition\RuntimeDefinition.php(286): Zend\Di\Definition\RuntimeDefinition->processParams(Array, Object(Zend\Code\Reflection\ClassReflection), Object(Zend\Code\Reflection\MethodReflection))
#3 vendor\zendframework\zendframework\library\Zend\Di\Definition\RuntimeDefinition.php(173): Zend\Di\Definition\Runti in vendor\zendframework\zendframework\library\Zend\Code\Reflection\ParameterReflection.php on line 47

**Comment by mwillbanks** [comment]
This was actually just fixed :)

**Comment by ghost** [comment]
Thank you!
