### ISSUE TITLE
Problem with initialisation

### ISSUE THREAD

**Issue by ghost** [mwillbanks/ZfcTwitterBootstrap#8]
Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (ZfcTwitterBootstrap) could not be initialized.'

**Comment by mwillbanks** [comment]
Interesting; is this on the released zf2 or is this on master?

**Comment by ghost** [comment]
on both.
installation by composer.

**Comment by mwillbanks** [comment]
Did you add this to config/application.config.php?  Inside of that configuration do you have module_paths set so that it references ./vendor?

I cannot seem to reproduce this in anyway.  Sorry it took me so long to get back to you.
